version: '3.8'

services:
  nexhealth-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nexhealth-proxy
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXHEALTH_API_KEY=${NEXHEALTH_API_KEY}
      - NEXHEALTH_SUBDOMAIN=${NEXHEALTH_SUBDOMAIN}
      - NEXHEALTH_LOCATION_ID=${NEXHEALTH_LOCATION_ID}
      - NEXHEALTH_PRACTICE_NAME=${NEXHEALTH_PRACTICE_NAME}
      - NEXHEALTH_SYNC_ID=${NEXHEALTH_SYNC_ID}
    volumes:
      - nexhealth-cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nexhealth-cache:
